"""delete admin rules

Revision ID: aae874dfbed1
Revises: d20f330bf216
Create Date: 2024-12-05 16:49:38.105503

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "aae874dfbed1"
down_revision: Union[str, None] = "d20f330bf216"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admins_rules")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins_rules",
        sa.Column("admin_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "rule",
            postgresql.ENUM("Rule", name="rule_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["admin_id"], ["admins.id"], name="admins_rules_admin_id_fkey"
        ),
        sa.PrimaryKeyConstraint("admin_id", "rule", name="admins_rules_pkey"),
    )
    # ### end Alembic commands ###
