"""index on users

Revision ID: 0b2b0201d2a0
Revises: f3e2abf20257
Create Date: 2024-12-04 20:10:05.054468

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0b2b0201d2a0"
down_revision: Union[str, None] = "f3e2abf20257"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_id_key", "users", type_="unique")
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.create_unique_constraint("users_id_key", "users", ["id"])
    # ### end Alembic commands ###
