"""added oauth2_clients

Revision ID: d20f330bf216
Revises: 0b2b0201d2a0
Create Date: 2024-12-05 16:33:23.214735

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d20f330bf216"
down_revision: Union[str, None] = "0b2b0201d2a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oauth2_clients",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("client_id", sa.String(length=48), nullable=False),
        sa.Column("client_secret", sa.String(length=120), nullable=False),
        sa.Column("redirect_uri", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("grant_type", sa.String(), nullable=True),
        sa.Column("response_type", sa.String(), nullable=True),
        sa.Column("token_endpoint_auth_method", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_oauth2_clients_client_id"),
        "oauth2_clients",
        ["client_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_oauth2_clients_client_id"), table_name="oauth2_clients"
    )
    op.drop_table("oauth2_clients")
    # ### end Alembic commands ###
